import { Job, Notification } from "./types"

export const mockNotifications: Notification[] = [
  {
    id: "1",
    type: "error",
    title: "Job Failed",
    message: "Data processing job #1234 failed due to insufficient memory.",
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    read: false,
  },
  {
    id: "2",
    type: "warning",
    title: "High CPU Usage",
    message: "Server CPU usage exceeded 90% threshold.",
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    read: false,
  },
  {
    id: "3",
    type: "info",
    title: "Scheduled Maintenance",
    message: "System maintenance scheduled for tomorrow at 2:00 AM.",
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    read: true,
  },
  {
    id: "4",
    type: "warning",
    title: "Storage Warning",
    message: "Storage capacity at 85%. Consider cleanup.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    read: false,
  },
  {
    id: "5",
    type: "info",
    title: "New Feature Available",
    message: "Job scheduling feature is now available.",
    timestamp: new Date(Date.now() - 1000 * 60 * 120),
    read: true,
  },
]

export const mockJobs: Job[] = [
  {
    id: "JOB-001",
    name: "Data Export",
    status: "completed",
    progress: 100,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 23),
    owner: "John Doe",
    priority: "high",
    description: "Export all user data to CSV format for quarterly reporting.",
  },
  {
    id: "JOB-002",
    name: "Image Processing",
    status: "running",
    progress: 65,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    updatedAt: new Date(Date.now() - 1000 * 60 * 5),
    owner: "Jane Smith",
    priority: "medium",
    description: "Batch resize and optimize images for web deployment.",
  },
  {
    id: "JOB-003",
    name: "Database Backup",
    status: "pending",
    progress: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30),
    owner: "Admin",
    priority: "high",
    description: "Full database backup to secure storage.",
  },
  {
    id: "JOB-004",
    name: "Report Generation",
    status: "failed",
    progress: 45,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
    owner: "Mike Johnson",
    priority: "low",
    description: "Generate monthly sales report with analytics.",
  },
  {
    id: "JOB-005",
    name: "Email Campaign",
    status: "completed",
    progress: 100,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 47),
    owner: "Sarah Lee",
    priority: "medium",
    description: "Send promotional emails to subscriber list.",
  },
  {
    id: "JOB-006",
    name: "Log Analysis",
    status: "running",
    progress: 30,
    createdAt: new Date(Date.now() - 1000 * 60 * 45),
    updatedAt: new Date(Date.now() - 1000 * 60 * 2),
    owner: "Dev Team",
    priority: "low",
    description: "Analyze server logs for security patterns.",
  },
  {
    id: "JOB-007",
    name: "API Sync",
    status: "cancelled",
    progress: 20,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 10),
    owner: "System",
    priority: "medium",
    description: "Synchronize data with third-party API.",
  },
  {
    id: "JOB-008",
    name: "Cache Refresh",
    status: "completed",
    progress: 100,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
    owner: "Admin",
    priority: "high",
    description: "Clear and rebuild application cache.",
  },
]
